In [1]:
import pandas as pd
import numpy as np 
import seaborn as sns
import matplotlib.pyplot as plt

In [2]:
df = pd.read_csv(r'C:\Users\shrey\SHLOK Python Code\MACHINE_LEARNING\GridSearchCV\Iris.csv')

In [3]:
df.head()

   Id  sepal_length  sepal_width  petal_length  petal_width species
0   1           5.1          3.5           1.4          0.2  setosa
1   2           4.9          3.0           1.4          0.2  setosa
2   3           4.7          3.2           1.3          0.2  setosa
3   4           4.6          3.1           1.5          0.2  setosa
4   5           5.0          3.6           1.4          0.2  setosa

In [4]:
df['species'].value_counts()

species
versicolor    69
setosa        41
virginica     40
Name: count, dtype: int64

In [5]:
df['species'].unique()

array(['setosa', 'versicolor', 'virginica'], dtype=object)

In [6]:
from sklearn.model_selection import train_test_split

In [7]:
X = df.drop('species', axis = 1)
y = df['species']

In [8]:
X

      Id  sepal_length  sepal_width  petal_length  petal_width
0      1           5.1          3.5           1.4          0.2
1      2           4.9          3.0           1.4          0.2
2      3           4.7          3.2           1.3          0.2
3      4           4.6          3.1           1.5          0.2
4      5           5.0          3.6           1.4          0.2
..   ...           ...          ...           ...          ...
145  146           6.7          3.0           5.2          2.3
146  147           6.3          2.5           5.0          1.9
147  148           6.5          3.0           5.2          2.0
148  149           6.2          3.4           5.4          2.3
149  150           5.9          3.0           5.1          1.8

[150 rows x 5 columns]

In [9]:
y

0         setosa
1         setosa
2         setosa
3         setosa
4         setosa
         ...
145    virginica
146    virginica
147    virginica
148    virginica
149    virginica
Name: species, Length: 150, dtype: object

In [10]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.33, random_state = 42)

In [11]:
from sklearn.neighbors import KNeighborsClassifier

In [12]:
model_knn = KNeighborsClassifier(n_neighbors=5)

In [13]:
model_knn.fit(X_train,y_train)

KNeighborsClassifier()

In [14]:
model_knn.score(X_test, y_test)

1.0

In [15]:
from sklearn.svm import SVC

In [16]:
model_svc = SVC(C = 10, kernel='rbf', gamma='auto')

In [17]:
model_svc.fit(X_train, y_train)

SVC(C=10, gamma='auto')

In [18]:
model_svc.score(X_test, y_test)

0.96

Grid Search Cv

In [19]:
from sklearn.model_selection import GridSearchCV

In [20]:
classifier = GridSearchCV((model_svc),{
    'C' : [1,10,20,30],
    'kernel' : ['rbf', 'linear'],
    
}, cv=5, return_train_score=False)

In [21]:
classifier.fit(X,y)

GridSearchCV(cv=5, estimator=SVC(C=10, gamma='auto'),
             param_grid={'C': [1, 10, 20, 30], 'kernel': ['rbf', 'linear']})

In [22]:
classifier.cv_results_

{'mean_fit_time': array([0.00510025, 0.00655575, 0.00741076, 0.022859  , 0.00550365,
        0.03590403, 0.00629692, 0.04273949]),
 'std_fit_time': array([0.00068341, 0.00217004, 0.00482616, 0.0110601 , 0.0007802 ,
        0.01881919, 0.00411802, 0.02048736]),
 'mean_score_time': array([0.00315967, 0.00312877, 0.0035687 , 0.00241718, 0.0034904 ,
        0.00251646, 0.00304003, 0.00227008]),
 'std_score_time': array([0.00025022, 0.00064834, 0.00064052, 0.00054033, 0.00057487,
        0.00081222, 0.00080851, 0.00048158]),
 'param_C': masked_array(data=[1, 1, 10, 10, 20, 20, 30, 30],
              mask=[False, False, False, False, False, False, False, False],
        fill_value=999999),
 'param_kernel': masked_array(data=['rbf', 'linear', 'rbf', 'linear', 'rbf', 'linear',
                    'rbf', 'linear'],
              mask=[False, False, False, False, False, False, False, False],
        fill_value=np.str_('?'),
             dtype=object),
 'params': [{'C': 1, 'kernel': 'rbf'},
  {'C': 1, 'kernel': 'linear'},
  {'C': 10, 'kernel': 'rbf'},
  {'C': 10, 'kernel': 'linear'},
  {'C': 20, 'kernel': 'rbf'},
  {'C': 20, 'kernel': 'linear'},
  {'C': 30, 'kernel': 'rbf'},
  {'C': 30, 'kernel': 'linear'}],
 'split0_test_score': array([0.46666667, 0.76666667, 0.46666667, 0.73333333, 0.46666667,
        0.73333333, 0.46666667, 0.73333333]),
 'split1_test_score': array([0.73333333, 1.        , 0.73333333, 1.        , 0.73333333,
        1.        , 0.73333333, 1.        ]),
 'split2_test_score': array([0.66666667, 1.        , 0.66666667, 0.96666667, 0.66666667,
        0.93333333, 0.66666667, 0.93333333]),
 'split3_test_score': array([0.73333333, 1.        , 0.73333333, 1.        , 0.73333333,
        1.        , 0.73333333, 0.96666667]),
 'split4_test_score': array([0.43333333, 0.5       , 0.43333333, 0.5       , 0.43333333,
        0.5       , 0.43333333, 0.5       ]),
 'mean_test_score': array([0.60666667, 0.85333333, 0.60666667, 0.84      , 0.60666667,
        0.83333333, 0.60666667, 0.82666667]),
 'std_test_score': array([0.13063945, 0.19843835, 0.13063945, 0.19708994, 0.13063945,
        0.19321836, 0.13063945, 0.18785337]),
 'rank_test_score': array([5, 1, 5, 2, 5, 3, 5, 4], dtype=int32)}

In [23]:
results = pd.DataFrame(classifier.cv_results_)

In [24]:
results

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_C,param_kernel,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.005100,0.000683,0.003160,0.000250,1,rbf,"{'C': 1, 'kernel': 'rbf'}",0.466667,0.733333,0.666667,0.733333,0.433333,0.606667,0.130639,5
1,0.006556,0.002170,0.003129,0.000648,1,linear,"{'C': 1, 'kernel': 'linear'}",0.766667,1.000000,1.000000,1.000000,0.500000,0.853333,0.198438,1
2,0.007411,0.004826,0.003569,0.000641,10,rbf,"{'C': 10, 'kernel': 'rbf'}",0.466667,0.733333,0.666667,0.733333,0.433333,0.606667,0.130639,5
3,0.022859,0.011060,0.002417,0.000540,10,linear,"{'C': 10, 'kernel': 'linear'}",0.733333,1.000000,0.966667,1.000000,0.500000,0.840000,0.197090,2
4,0.005504,0.000780,0.003490,0.000575,20,rbf,"{'C': 20, 'kernel': 'rbf'}",0.466667,0.733333,0.666667,0.733333,0.433333,0.606667,0.130639,5
5,0.035904,0.018819,0.002516,0.000812,20,linear,"{'C': 20, 'kernel': 'linear'}",0.733333,1.000000,0.933333,1.000000,0.500000,0.833333,0.193218,3
6,0.006297,0.004118,0.003040,0.000809,30,rbf,"{'C': 30, 'kernel': 'rbf'}",0.466667,0.733333,0.666667,0.733333,0.433333,0.606667,0.130639,5
7,0.042739,0.020487,0.002270,0.000482,30,linear,"{'C': 30, 'kernel': 'linear'}",0.733333,1.000000,0.933333,0.966667,0.500000,0.826667,0.187853,4

In [25]:
results[['param_C', 'param_kernel','mean_test_score']]

   param_C param_kernel  mean_test_score
0        1          rbf         0.606667
1        1       linear         0.853333
2       10          rbf         0.606667
3       10       linear         0.840000
4       20          rbf         0.606667
5       20       linear         0.833333
6       30          rbf         0.606667
7       30       linear         0.826667

In [26]:
classifier = GridSearchCV((model_knn), {
    'n_neighbors': np.arange(1, 21)
    
},cv=5, return_train_score=False)

In [27]:
classifier.fit(X,y)

GridSearchCV(cv=5, estimator=KNeighborsClassifier(),
             param_grid={'n_neighbors': array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])})

In [28]:
classifier.cv_results_

{'mean_fit_time': array([0.00259204, 0.00262446, 0.0029737 , 0.00299158, 0.00240374,
        0.00440688, 0.00337224, 0.00204701, 0.00249848, 0.00354543,
        0.00248852, 0.00214157, 0.00221949, 0.00245028, 0.00222635,
        0.00271435, 0.00323009, 0.00277267, 0.00263   , 0.00255375]),
 'std_fit_time': array([0.00023987, 0.00044324, 0.00077175, 0.00041654, 0.00035524,
        0.00275558, 0.0009461 , 0.00035923, 0.00124203, 0.00142026,
        0.00054642, 0.00021712, 0.00021087, 0.0005932 , 0.0002955 ,
        0.00076894, 0.00028722, 0.00057883, 0.00064304, 0.0003783 ]),
 'mean_score_time': array([0.00336347, 0.00415874, 0.00393248, 0.00430927, 0.00419116,
        0.00560312, 0.00375986, 0.00288057, 0.00296745, 0.00440874,
        0.0032238 , 0.00304723, 0.00314727, 0.00316219, 0.00344448,
        0.00372567, 0.00496097, 0.00403228, 0.00371604, 0.00380611]),
 'std_score_time': array([0.00060776, 0.00081714, 0.00051132, 0.00051361, 0.00099057,
        0.0041981 , 0.00051003, 0.00059839, 0.0005718 , 0.00112893,
        0.00038816, 0.00043284, 0.00043839, 0.0002428 , 0.00064109,
        0.00096007, 0.0008564 , 0.000799  , 0.00059824, 0.00077846]),
 'param_n_neighbors': masked_array(data=[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16,
                    17, 18, 19, 20],
              mask=[False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False],
        fill_value=999999),
 'params': [{'n_neighbors': np.int64(1)},
  {'n_neighbors': np.int64(2)},
  {'n_neighbors': np.int64(3)},
  {'n_neighbors': np.int64(4)},
  {'n_neighbors': np.int64(5)},
  {'n_neighbors': np.int64(6)},
  {'n_neighbors': np.int64(7)},
  {'n_neighbors': np.int64(8)},
  {'n_neighbors': np.int64(9)},
  {'n_neighbors': np.int64(10)},
  {'n_neighbors': np.int64(11)},
  {'n_neighbors': np.int64(12)},
  {'n_neighbors': np.int64(13)},
  {'n_neighbors': np.int64(14)},
  {'n_neighbors': np.int64(15)},
  {'n_neighbors': np.int64(16)},
  {'n_neighbors': np.int64(17)},
  {'n_neighbors': np.int64(18)},
  {'n_neighbors': np.int64(19)},
  {'n_neighbors': np.int64(20)}],
 'split0_test_score': array([0.63333333, 0.63333333, 0.63333333, 0.63333333, 0.63333333,
        0.63333333, 0.63333333, 0.63333333, 0.63333333, 0.63333333,
        0.63333333, 0.63333333, 0.63333333, 0.63333333, 0.63333333,
        0.63333333, 0.63333333, 0.6       , 0.63333333, 0.63333333]),
 'split1_test_score': array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1.]),
 'split2_test_score': array([0.9       , 0.83333333, 0.83333333, 0.83333333, 0.83333333,
        0.83333333, 0.9       , 0.83333333, 0.83333333, 0.83333333,
        0.9       , 0.83333333, 0.9       , 0.83333333, 0.9       ,
        0.83333333, 0.9       , 0.83333333, 0.86666667, 0.83333333]),
 'split3_test_score': array([1.        , 1.        , 1.        , 1.        , 1.        ,
        0.93333333, 0.96666667, 0.96666667, 0.86666667, 0.9       ,
        0.86666667, 0.86666667, 0.86666667, 0.86666667, 0.86666667,
        0.9       , 0.86666667, 0.86666667, 0.86666667, 0.9       ]),
 'split4_test_score': array([0.5       , 0.5       , 0.46666667, 0.5       , 0.5       ,
        0.53333333, 0.46666667, 0.53333333, 0.46666667, 0.53333333,
        0.5       , 0.5       , 0.46666667, 0.53333333, 0.46666667,
        0.53333333, 0.46666667, 0.53333333, 0.46666667, 0.53333333]),
 'mean_test_score': array([0.80666667, 0.79333333, 0.78666667, 0.79333333, 0.79333333,
        0.78666667, 0.79333333, 0.79333333, 0.76      , 0.78      ,
        0.78      , 0.76666667, 0.77333333, 0.77333333, 0.77333333,
        0.78      , 0.77333333, 0.76666667, 0.76666667, 0.78      ]),
 'std_test_score': array([0.20374276, 0.19933222, 0.20933758, 0.19933222, 0.19933222,
        0.17713774, 0.20805982, 0.1830604 , 0.18785337, 0.17204651,
        0.18451137, 0.17763883, 0.19482186, 0.16786238, 0.19482186,
        0.17204651, 0.19482186, 0.1738454 , 0.19090428, 0.17204651]),
 'rank_test_score': array([ 1,  2,  7,  2,  2,  7,  2,  2, 20,  9,  9, 17, 13, 13, 13,  9, 13,
        17, 17,  9], dtype=int32)}

In [29]:
result_knn = pd.DataFrame(classifier.cv_results_)

In [30]:
result_knn

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_n_neighbors,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.002592,0.000240,0.003363,0.000608,1,{'n_neighbors': 1},0.633333,1.0,0.900000,1.000000,0.500000,0.806667,0.203743,1
1,0.002624,0.000443,0.004159,0.000817,2,{'n_neighbors': 2},0.633333,1.0,0.833333,1.000000,0.500000,0.793333,0.199332,2
2,0.002974,0.000772,0.003932,0.000511,3,{'n_neighbors': 3},0.633333,1.0,0.833333,1.000000,0.466667,0.786667,0.209338,7
3,0.002992,0.000417,0.004309,0.000514,4,{'n_neighbors': 4},0.633333,1.0,0.833333,1.000000,0.500000,0.793333,0.199332,2
4,0.002404,0.000355,0.004191,0.000991,5,{'n_neighbors': 5},0.633333,1.0,0.833333,1.000000,0.500000,0.793333,0.199332,2
5,0.004407,0.002756,0.005603,0.004198,6,{'n_neighbors': 6},0.633333,1.0,0.833333,0.933333,0.533333,0.786667,0.177138,7
6,0.003372,0.000946,0.003760,0.000510,7,{'n_neighbors': 7},0.633333,1.0,0.900000,0.966667,0.466667,0.793333,0.208060,2
7,0.002047,0.000359,0.002881,0.000598,8,{'n_neighbors': 8},0.633333,1.0,0.833333,0.966667,0.533333,0.793333,0.183060,2
8,0.002498,0.001242,0.002967,0.000572,9,{'n_neighbors': 9},0.633333,1.0,0.833333,0.866667,0.466667,0.760000,0.187853,20
9,0.003545,0.001420,0.004409,0.001129,10,{'n_neighbors': 10},0.633333,1.0,0.833333,0.900000,0.533333,0.780000,0.172047,9
10,0.002489,0.000546,0.003224,0.000388,11,{'n_neighbors': 11},0.633333,1.0,0.900000,0.866667,0.500000,0.780000,0.184511,9
11,0.002142,0.000217,0.003047,0.000433,12,{'n_neighbors': 12},0.633333,1.0,0.833333,0.866667,0.500000,0.766667,0.177639,17
12,0.002219,0.000211,0.003147,0.000438,13,{'n_neighbors': 13},0.633333,1.0,0.900000,0.866667,0.466667,0.773333,0.194822,13
13,0.002450,0.000593,0.003162,0.000243,14,{'n_neighbors': 14},0.633333,1.0,0.833333,0.866667,0.533333,0.773333,0.167862,13
14,0.002226,0.000296,0.003444,0.000641,15,{'n_neighbors': 15},0.633333,1.0,0.900000,0.866667,0.466667,0.773333,0.194822,13
15,0.002714,0.000769,0.003726,0.000960,16,{'n_neighbors': 16},0.633333,1.0,0.833333,0.900000,0.533333,0.780000,0.172047,9
16,0.003230,0.000287,0.004961,0.000856,17,{'n_neighbors': 17},0.633333,1.0,0.900000,0.866667,0.466667,0.773333,0.194822,13
17,0.002773,0.000579,0.004032,0.000799,18,{'n_neighbors': 18},0.600000,1.0,0.833333,0.866667,0.533333,0.766667,0.173845,17
18,0.002630,0.000643,0.003716,0.000598,19,{'n_neighbors': 19},0.633333,1.0,0.866667,0.866667,0.466667,0.766667,0.190904,17
19,0.002554,0.000378,0.003806,0.000778,20,{'n_neighbors': 20},0.633333,1.0,0.833333,0.900000,0.533333,0.780000,0.172047,9

In [31]:
result_knn[['mean_test_score']]

    mean_test_score
0          0.806667
1          0.793333
2          0.786667
3          0.793333
4          0.793333
5          0.786667
6          0.793333
7          0.793333
8          0.760000
9          0.780000
10         0.780000
11         0.766667
12         0.773333
13         0.773333
14         0.773333
15         0.780000
16         0.773333
17         0.766667
18         0.766667
19         0.780000

In [32]:
from sklearn.model_selection import RandomizedSearchCV

In [33]:
classifier_rsv = RandomizedSearchCV((model_svc),{
    'C' : [1,10,20,30],
    'kernel' : ['rbf', 'linear'],
    
},n_iter=  4, cv=5, return_train_score=False)

In [34]:
classifier_rsv.fit(X,y)

RandomizedSearchCV(cv=5, estimator=SVC(C=10, gamma='auto'), n_iter=4,
                   param_distributions={'C': [1, 10, 20, 30],
                                        'kernel': ['rbf', 'linear']})

In [35]:
classifier_rsv.cv_results_

{'mean_fit_time': array([0.00383368, 0.03806043, 0.00464478, 0.04364285]),
 'std_fit_time': array([0.00074429, 0.02261044, 0.00064271, 0.02372048]),
 'mean_score_time': array([0.00243759, 0.00239062, 0.00302129, 0.0024539 ]),
 'std_score_time': array([0.00057693, 0.00061884, 0.0007286 , 0.00054803]),
 'param_kernel': masked_array(data=['rbf', 'linear', 'rbf', 'linear'],
              mask=[False, False, False, False],
        fill_value=np.str_('?'),
             dtype=object),
 'param_C': masked_array(data=[30, 20, 1, 30],
              mask=[False, False, False, False],
        fill_value=999999),
 'params': [{'kernel': 'rbf', 'C': 30},
  {'kernel': 'linear', 'C': 20},
  {'kernel': 'rbf', 'C': 1},
  {'kernel': 'linear', 'C': 30}],
 'split0_test_score': array([0.46666667, 0.73333333, 0.46666667, 0.73333333]),
 'split1_test_score': array([0.73333333, 1.        , 0.73333333, 1.        ]),
 'split2_test_score': array([0.66666667, 0.93333333, 0.66666667, 0.93333333]),
 'split3_test_score': array([0.73333333, 1.        , 0.73333333, 0.96666667]),
 'split4_test_score': array([0.43333333, 0.5       , 0.43333333, 0.5       ]),
 'mean_test_score': array([0.60666667, 0.83333333, 0.60666667, 0.82666667]),
 'std_test_score': array([0.13063945, 0.19321836, 0.13063945, 0.18785337]),
 'rank_test_score': array([3, 1, 3, 2], dtype=int32)}

In [36]:
result =pd.DataFrame(classifier_rsv.cv_results_)

In [37]:
result

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_kernel,param_C,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.003834,0.000744,0.002438,0.000577,rbf,30,"{'kernel': 'rbf', 'C': 30}",0.466667,0.733333,0.666667,0.733333,0.433333,0.606667,0.130639,3
1,0.038060,0.022610,0.002391,0.000619,linear,20,"{'kernel': 'linear', 'C': 20}",0.733333,1.000000,0.933333,1.000000,0.500000,0.833333,0.193218,1
2,0.004645,0.000643,0.003021,0.000729,rbf,1,"{'kernel': 'rbf', 'C': 1}",0.466667,0.733333,0.666667,0.733333,0.433333,0.606667,0.130639,3
3,0.043643,0.023720,0.002454,0.000548,linear,30,"{'kernel': 'linear', 'C': 30}",0.733333,1.000000,0.933333,0.966667,0.500000,0.826667,0.187853,2

In [38]:
results[['param_C', 'param_kernel','mean_test_score']]

   param_C param_kernel  mean_test_score
0        1          rbf         0.606667
1        1       linear         0.853333
2       10          rbf         0.606667
3       10       linear         0.840000
4       20          rbf         0.606667
5       20       linear         0.833333
6       30          rbf         0.606667
7       30       linear         0.826667