In [1]:
import pandas as pd
import warnings
warnings.filterwarnings('ignore')

df = pd.read_csv(r'C:\Users\shrey\SHLOK Python Code\ETL\Day-1\employees.csv')

In [2]:
df.head()

    name department   salary   age
0  Rahul         IT  60000.0  26.0
1  Priya         HR  45000.0  28.0
2   Amit    Finance  55000.0  32.0
3   Neha         IT  70000.0  30.0
4  Karan  Marketing  50000.0  27.0

In [3]:
df.isnull().sum()

name          0
department    0
salary        1
age           1
dtype: int64

In [4]:
df['salary'].fillna(df['salary'].mean(), inplace=True)

In [5]:
df['age'].fillna(df['age'].mean(), inplace=True)

In [6]:
df

     name department        salary        age
0   Rahul         IT  60000.000000  26.000000
1   Priya         HR  45000.000000  28.000000
2    Amit    Finance  55000.000000  32.000000
3    Neha         IT  70000.000000  30.000000
4   Karan  Marketing  50000.000000  27.000000
5  Anjali         IT  55333.333333  29.000000
6   Vikas    Finance  52000.000000  28.666667

In [7]:
df['salary'] = df['salary'].astype(int)
df['age'] = df['age'].astype(int)

In [8]:
df

     name department  salary  age
0   Rahul         IT   60000   26
1   Priya         HR   45000   28
2    Amit    Finance   55000   32
3    Neha         IT   70000   30
4   Karan  Marketing   50000   27
5  Anjali         IT   55333   29
6   Vikas    Finance   52000   28

In [9]:
def categorical_column(salary):
    if salary > 65000:
        return 'High'
    
    elif salary >= 50000:
        return ' Medium'
    else:
        return 'Low'

In [10]:
df['salary_category'] = df['salary'].apply(categorical_column)

In [11]:
df

     name department  salary  age salary_category
0   Rahul         IT   60000   26          Medium
1   Priya         HR   45000   28             Low
2    Amit    Finance   55000   32          Medium
3    Neha         IT   70000   30            High
4   Karan  Marketing   50000   27          Medium
5  Anjali         IT   55333   29          Medium
6   Vikas    Finance   52000   28          Medium

In [12]:
df.duplicated().sum()

np.int64(0)

In [13]:
df.drop_duplicates(inplace=True)

In [14]:
df

     name department  salary  age salary_category
0   Rahul         IT   60000   26          Medium
1   Priya         HR   45000   28             Low
2    Amit    Finance   55000   32          Medium
3    Neha         IT   70000   30            High
4   Karan  Marketing   50000   27          Medium
5  Anjali         IT   55333   29          Medium
6   Vikas    Finance   52000   28          Medium

In [15]:
import psycopg2

conn = psycopg2.connect(
    host="localhost",
    database="company_db",
    user="postgres",
    password="your_password"
)

cursor = conn.cursor()

OperationalError: connection to server at "localhost" (::1), port 5432 failed: Connection refused (0x0000274D/10061)
	Is the server running on that host and accepting TCP/IP connections?
connection to server at "localhost" (127.0.0.1), port 5432 failed: Connection refused (0x0000274D/10061)
	Is the server running on that host and accepting TCP/IP connections?